services:
  postgres_db:
    image: postgres:15-alpine
    container_name: ecom_postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_secure_password_2026
      POSTGRES_DB: ecommerce_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d ecommerce_db']
      interval: 10s
      timeout: 5s
      retries: 5

  api_backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecom_nestjs_api
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://postgres:postgres_secure_password_2026@postgres_db:5432/ecommerce_db
      PAYMENT_PROVIDER_BASE_URL: ${PAYMENT_PROVIDER_BASE_URL}
      PAYMENT_PROVIDER_PUBLIC_KEY: ${PAYMENT_PROVIDER_PUBLIC_KEY}
      PAYMENT_PROVIDER_PRIVATE_KEY: ${PAYMENT_PROVIDER_PRIVATE_KEY}
      PAYMENT_PROVIDER_EVENTS_KEY: ${PAYMENT_PROVIDER_EVENTS_KEY}
      PAYMENT_PROVIDER_INTEGRITY_SECRET: ${PAYMENT_PROVIDER_INTEGRITY_SECRET}
      PAYMENT_PROVIDER_MERCHANT_ID: ${PAYMENT_PROVIDER_MERCHANT_ID}
    depends_on:
      postgres_db:
        condition: service_healthy

  pgweb:
    image: sosedoff/pgweb:latest
    container_name: ecom_pgweb
    ports:
      - '8082:8082'
    command: >
      pgweb
      --url=postgresql://postgres:postgres_secure_password_2026@postgres_db:5432/ecommerce_db?sslmode=disable
      --bind=0.0.0.0
      --listen=8082
    depends_on:
      - postgres_db

  mobile_builder:
    build:
      context: .
      dockerfile: mobile/Dockerfile
    container_name: mobile_builder
    volumes:
      - ./mobile/build:/out
    command: sh -c "mkdir -p /out && cp /app/mobile/app-mobile.apk /out/app-mobile.apk"

volumes:
  postgres_data:
